name: 'Merge coverage reports'
author: 'selfagency'
description: 'Merge Istanbul coverage reports'
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  coverage-reports:
    description: 'Path to coverage reports'
    type: string
    required: true
  output-folder:
    description: 'Where to output results'
    type: string
    required: true
  formats:
    description: 'Comma-separated list of formats to output'
    type: string
    required: true
outputs:
  summary:
    description: 'Coverage summary'
    value: steps.merge-coverage.outputs.summary
  json:
    description: 'JSON coverage summary'
    value: steps.merge-coverage.outputs.json
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Merge coverage reports
      shell: bash
      run: |
        ln -s ${{ inputs.coverage-reports }} .nyc_output
        ${{ github.workspace }}/node_modules/.bin/nyc merge .nyc_output .nyc_output/out.json

    - name: Configure reporters
      id: configure-reporters
      uses: actions/github-script@v6
      if: ${{ !steps.merge-coverage.outputs.skip }}
      with:
        script: |
          const reporters = '${{ inputs.formats }}'.split(',');
          let reporterConfig = '';
          reporters.forEach(reporter => {
            reporterConfig += `--reporter ${reporter} `;
          });
          core.setOutput('reporters', reporterConfig);

    - name: Output coverage reports
      shell: bash
      if: ${{ !steps.merge-coverage.outputs.skip }}
      run: |
        cat .nyc_output/out.json
        ${{ github.workspace }}/node_modules/.bin/nyc report --reporter json-summary --reporter text-summary ${{ steps.configure-reporters.outputs.reporters }} --reportDir ${{ inputs.output-folder }}
        echo "::set-output name=json::$(cat ${{ inputs.output-folder }}/coverage-summary.json)"

    - name: Upload coverage reports
      uses: actions/upload-artifact@v2
      if: ${{ !steps.merge-coverage.outputs.skip }}
      with:
        name: coverage-reports
        path: |
          ${{ inputs.output-folder }}
          ${{ github.workspace }}/.nyc_output
