name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Test action
        uses: selfagency/merge-coverage@main
        with:
          coverage-reports: ${{ github.workspace }}/testdata
          output-folder: ${{ github.workspace }}/testresults
          formats: lcov,json,html