name: Test
on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check package version
        id: check
        uses: 'EndBug/version-check@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Test action
        uses: selfagency/merge-coverage@v${{ steps.check.outputs.version}}
        with:
          coverage-reports: ${{ github.workspace }}/testdata
          output-folder: ${{ github.workspace }}/testresults
          formats: lcov,json,html